language: node_js
node_js:
  - "8.1.2"


branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - npm install
  - npm start

after_success:
  - firebase deploy --token $FIREBASE_TOKEN